apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2
  namespace: argocd
spec:
  destination:
    namespace: simplenode-dev
    name: in-cluster
  project: default
  source:
    path: demo2
    repoURL: https://github.com/grabnerandi/argocd-keptn-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true