apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginxdemo
  namespace: nginxdemo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  podMetricsEndpoints:
  - port: http
    interval: 5s
    scrapeTimeout: 4s
