apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: simplenode
  namespace: simplenode-dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: simplenodeservice
  podMetricsEndpoints:
  - port: promproxy
    interval: 5s
    scrapeTimeout: 4s
