apiVersion: v1
kind: Service
metadata:
  name: simplenode
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 32000
  selector:
    app.kubernetes.io/name: simplenodeservice