apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: grafana
namespace: monitoring

resources:
- ./dashboards/grafana-dashboard-keptn-applications.yaml
- ./dashboards/grafana-dashboard-keptn-overview.yaml
- ./dashboards/grafana-dashboard-keptn-workloads.yaml
- ./datasources.yaml