apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: grafana
namespace: monitoring

resources:
- https://raw.githubusercontent.com/keptn/lifecycle-toolkit/keptn-v0.10.0/examples/support/observability/config/prometheus/grafana-config.yaml
- https://raw.githubusercontent.com/keptn/lifecycle-toolkit/keptn-v0.10.0/examples/support/observability/config/prometheus/grafana-dashboard-keptn-applications.yaml
- https://raw.githubusercontent.com/keptn/lifecycle-toolkit/keptn-v0.10.0/examples/support/observability/config/prometheus/grafana-dashboard-keptn-overview.yaml
- https://raw.githubusercontent.com/keptn/lifecycle-toolkit/keptn-v0.10.0/examples/support/observability/config/prometheus/grafana-dashboard-keptn-workloads.yaml
- ./datasources.yaml
# - ./service.yaml