apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: grafana
namespace: monitoring

resources:
- https://raw.githubusercontent.com/keptn/lifecycle-toolkit/main/dashboards/grafana/configmap/grafana-dashboard-keptn-applications.yaml
- https://raw.githubusercontent.com/keptn/lifecycle-toolkit/main/dashboards/grafana/configmap/grafana-dashboard-keptn-overview.yaml
- https://raw.githubusercontent.com/keptn/lifecycle-toolkit/main/dashboards/grafana/configmap/grafana-dashboard-keptn-workloads.yaml
- ./datasources.yaml
- ./service.yaml