apiVersion: v1
kind: Service
metadata:
  name: lifecycle-operator-metrics-service
spec:
  ports:
  - name: metrics
    port: 2222
    protocol: TCP
    targetPort: 8080
    nodePort: 31444
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-operator-service
spec:
  ports:
  - name: metrics
    port: 9999
    protocol: TCP
    targetPort: 8080
    nodePort: 31446
  type: NodePort