apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
namespace: monitoring

patches:
  - path: ./service.yaml

helmCharts:
- name: kube-prometheus-stack
  releaseName: observability-stack
  namespace: monitoring
  version: 48.1.1
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: true
  valuesInline:
    grafana:
      adminPassword: admin
      sidecar.datasources.defaultDatasourceEnabled: false
    prometheus:
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: "scrape_klt"
            scrape_interval: 5s
            static_configs:
              - targets: ['lifecycle-operator-metrics-service.keptn-lifecycle-toolkit-system.svc.cluster.local:2222','metrics-operator-service.keptn-lifecycle-toolkit-system.svc.cluster.local:9999']