apiVersion: v1
kind: Namespace
metadata:
  name: podtato-kubectl
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-entry
  namespace: podtato-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head-entry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head-entry
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.2.8
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: ghcr.io/podtato-head/entry:0.2.8  # 0.2.8-0.2.17
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: PODTATO_PORT
          value: "9000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-hat
  namespace: podtato-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head-hat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head-hat
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.2.8
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image:  ghcr.io/podtato-head/hat:0.2.8  # 0.2.8-0.2.17
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: PODTATO_PORT
              value: "9000"
