apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keptn
spec:
  destination:
    name: in-cluster
    namespace: keptn-lifecycle-toolkit-system
  source:
    repoURL: 'https://charts.lifecycle.keptn.sh'
    targetRevision: 0.3.0
    chart: keptn
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
